---
- hosts: mgr1
  become: true
  tasks:

    - name: Join command for Worker
      shell: docker swarm init --advertise-addr "<<manager1_ip_address>>"
      register: swarm_worker_output
      changed_when: false

    - name: Extract Join Command
      set_fact:
              join_command_worker: "{{ swarm_worker_output.stdout_lines[4] | regex_replace('^\\s+', '')}}"

    - name: Display Join Command
      debug:
        var: join_command_worker

    - name: Join command for Manager
      shell: 'docker swarm join-token manager | grep join'
      register: swarm_manager_output
      changed_when: false

    - name: Extract Join Command
      set_fact:
              join_command_manager: "{{ swarm_manager_output.stdout_lines[0] | regex_replace('^\\s+', '') }}"

    - name: Display Join Command
      debug:
        var: join_command_manager


    - name: Save Output to File
      copy:
        content: "{{ join_command_worker }}"
        dest: "/home/worker.txt"
 
    - name: Copy File to Ansible Control Machine
      fetch:
        src: /home/worker.txt
        dest: /home/worker.txt
        flat: yes

    - name: Save Output to File
      copy:
        content: "{{ join_command_manager }}"
        dest: "/home/manager.txt"

    - name: Copy File to Ansible Control Machine
      fetch:
        src: /home/manager.txt
        dest: /home/manager.txt
        flat: yes
